
"use client";

import { useState, useRef, useEffect } from "react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Textarea } from "@/components/ui/textarea";
import { Paperclip, Send, Bot, User, Mic, Link as LinkIcon, Library, Plus, ArrowUp, ArrowDown } from "lucide-react";
import { ChatMessage } from "./chat-message";
import { InitialPrompts } from "./initial-prompts";
import type { Message } from "./chat-message";
import { PlaceHolderImages } from "@/lib/placeholder-images";
import { cn } from "@/lib/utils";

export function ChatInterface() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [isScrolledToBottom, setIsScrolledToBottom] = useState(true);
  const [isAtTop, setIsAtTop] = useState(true);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const scrollViewportRef = useRef<HTMLDivElement>(null);
  const userAvatar = PlaceHolderImages.find(p => p.id === 'user-avatar');
  const aiAvatar = PlaceHolderImages.find(p => p.id === 'ai-avatar');

  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = "auto";
      const scrollHeight = textareaRef.current.scrollHeight;
      const maxHeight = 200; // max height 
      textareaRef.current.style.height = `${Math.min(scrollHeight, maxHeight)}px`;
    }
  }, [input]);

  useEffect(() => {
    const viewport = scrollViewportRef.current;
    if (viewport && isScrolledToBottom) {
      viewport.scrollTop = viewport.scrollHeight;
    }
  }, [messages, isScrolledToBottom]);


  const handleSend = () => {
    if (input.trim() === "") return;

    const userMessage: Message = {
      id: Date.now().toString(),
      sender: "user",
      content: input,
      avatar: (
        <Avatar className="h-8 w-8">
          {userAvatar && <AvatarImage src={userAvatar.imageUrl} alt="User" data-ai-hint={userAvatar.imageHint} />}
          <AvatarFallback><User className="h-4 w-4" /></AvatarFallback>
        </Avatar>
      ),
    };

    const aiMessage: Message = {
      id: (Date.now() + 1).toString(),
      sender: "ai",
      content: "This is a placeholder response from the AI. The actual response would be generated by the selected model. This is a longer response to test the scrolling behavior and make sure everything works as expected. Let's add even more text to see how it handles multiple lines and overflow.",
      avatar: (
        <Avatar className="h-8 w-8">
          {aiAvatar && <AvatarImage src={aiAvatar.imageUrl} alt="AI" data-ai-hint={aiAvatar.imageHint} />}
          <AvatarFallback><Bot className="h-4 w-4" /></AvatarFallback>
        </Avatar>
      ),
    };

    setMessages((prev) => [...prev, userMessage, aiMessage]);
    setInput("");
    setIsScrolledToBottom(true);
  };

  const handlePromptClick = (prompt: string) => {
    setInput(prompt);
    // Automatically focus the textarea after clicking a prompt
    textareaRef.current?.focus();
  };
  
  const handleScroll = () => {
    const viewport = scrollViewportRef.current;
    if (viewport) {
      const isAtBottom = viewport.scrollHeight - viewport.scrollTop - viewport.clientHeight < 1;
      setIsScrolledToBottom(isAtBottom);
      const isAtTop = viewport.scrollTop === 0;
      setIsAtTop(isAtTop);
    }
  };

  const scrollToBottom = () => {
    scrollViewportRef.current?.scrollTo({ top: scrollViewportRef.current.scrollHeight, behavior: 'smooth' });
  };
  
  const scrollToTop = () => {
    scrollViewportRef.current?.scrollTo({ top: 0, behavior: 'smooth' });
  }
  
  return (
    <div className="flex flex-col flex-1 bg-card overflow-hidden">
        <div className="flex-1 relative">
            <ScrollArea className="h-full absolute inset-0" viewportRef={scrollViewportRef} onScroll={handleScroll}>
                <div className="max-w-4xl mx-auto w-full space-y-6 p-4">
                {messages.length === 0 ? (
                    <InitialPrompts onPromptClick={handlePromptClick} />
                ) : (
                    messages.map((msg) => <ChatMessage key={msg.id} message={msg} />)
                )}
                </div>
            </ScrollArea>
             {messages.length > 0 && !isAtTop && (
                 <Button 
                    onClick={scrollToTop}
                    variant="outline" 
                    size="icon"
                    className="absolute bottom-4 right-16 rounded-full z-10"
                >
                    <ArrowUp className="h-4 w-4" />
                </Button>
            )}
             {!isScrolledToBottom && (
                <Button 
                    onClick={scrollToBottom}
                    variant="outline" 
                    size="icon"
                    className="absolute bottom-4 right-4 rounded-full z-10"
                >
                    <ArrowDown className="h-4 w-4" />
                </Button>
            )}
        </div>


      <footer className="p-4 border-t border-border/20">
        <div className="max-w-4xl mx-auto w-full space-y-4">
            <div className="flex gap-2">
                <Button variant="outline" className="bg-background">
                    <Library className="mr-2 h-4 w-4" />
                    Library
                </Button>
                <Button variant="outline" className="bg-background">
                    <Plus className="mr-2 h-4 w-4" />
                    Add Context
                </Button>
                 <Button variant="outline" size="icon" className="bg-background">
                    <LinkIcon className="h-4 w-4" />
                 </Button>
                 <Button variant="outline" size="icon" className="bg-background">
                    <Mic className="h-4 w-4" />
                 </Button>
            </div>
          <div className="relative">
            <Textarea
              ref={textareaRef}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  handleSend();
                }
              }}
              placeholder="Send message"
              className="pr-28 text-base resize-none"
              rows={1}
            />
            <div className="absolute top-1/2 right-2 transform -translate-y-1/2 flex items-center">
              <Button size="lg" onClick={handleSend} disabled={!input.trim()} className="bg-primary text-primary-foreground h-9">
                <Send className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
