"use client";

import { useState } from "react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Textarea } from "@/components/ui/textarea";
import { Paperclip, Send, Bot, User } from "lucide-react";
import { ModelSelector } from "./model-selector";
import { TokenTracker } from "./token-tracker";
import { ChatMessage } from "./chat-message";
import { InitialPrompts } from "./initial-prompts";
import { PlaceHolderImages } from "@/lib/placeholder-images";
import type { Message } from "./chat-message";

export function ChatInterface() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const aiAvatar = PlaceHolderImages.find((img) => img.id === "ai-avatar");
  const userAvatar = PlaceHolderImages.find((img) => img.id === "user-avatar");

  const handleSend = () => {
    if (input.trim() === "") return;

    const userMessage: Message = {
      id: Date.now().toString(),
      sender: "user",
      content: input,
      avatar: (
        <Avatar className="h-8 w-8">
          {userAvatar && <AvatarImage src={userAvatar.imageUrl} alt="User" data-ai-hint={userAvatar.imageHint} />}
          <AvatarFallback><User className="h-4 w-4" /></AvatarFallback>
        </Avatar>
      ),
    };

    const aiMessage: Message = {
      id: (Date.now() + 1).toString(),
      sender: "ai",
      content: "This is a placeholder response from the AI. The actual response would be generated by the selected model.",
      avatar: (
        <Avatar className="h-8 w-8">
          {aiAvatar && <AvatarImage src={aiAvatar.imageUrl} alt="AI" data-ai-hint={aiAvatar.imageHint} />}
          <AvatarFallback><Bot className="h-4 w-4" /></AvatarFallback>
        </Avatar>
      ),
    };

    setMessages((prev) => [...prev, userMessage, aiMessage]);
    setInput("");
  };

  const handlePromptClick = (prompt: string) => {
    setInput(prompt);
  };
  
  return (
    <div className="flex flex-col h-full">
      <header className="flex items-center justify-between p-4 border-b">
        <h2 className="text-xl font-semibold">Chat</h2>
        <ModelSelector />
      </header>

      <ScrollArea className="flex-1 p-4">
        <div className="max-w-4xl mx-auto w-full space-y-6">
          {messages.length === 0 ? (
            <InitialPrompts onPromptClick={handlePromptClick} />
          ) : (
            messages.map((msg) => <ChatMessage key={msg.id} message={msg} />)
          )}
        </div>
      </ScrollArea>

      <footer className="p-4 border-t">
        <div className="max-w-4xl mx-auto w-full space-y-4">
          <div className="relative">
            <Textarea
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  handleSend();
                }
              }}
              placeholder="Ask a question or type '/' for commands..."
              className="pr-24 min-h-[4rem]"
            />
            <div className="absolute bottom-3 right-3 flex items-center gap-2">
              <Button variant="ghost" size="icon">
                <Paperclip className="h-5 w-5" />
                <span className="sr-only">Attach file</span>
              </Button>
              <Button size="icon" onClick={handleSend} disabled={!input.trim()}>
                <Send className="h-5 w-5" />
                <span className="sr-only">Send</span>
              </Button>
            </div>
          </div>
          <TokenTracker />
        </div>
      </footer>
    </div>
  );
}
