
"use client";

import { useState, useRef, useEffect } from "react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Textarea } from "@/components/ui/textarea";
import { Paperclip, Send, Bot, User, Mic, Link as LinkIcon, Library, Plus } from "lucide-react";
import { ChatMessage } from "./chat-message";
import { InitialPrompts } from "./initial-prompts";
import type { Message } from "./chat-message";
import { Input } from "../ui/input";
import { PlaceHolderImages } from "@/lib/placeholder-images";

export function ChatInterface() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const userAvatar = PlaceHolderImages.find(p => p.id === 'user-avatar');
  const aiAvatar = PlaceHolderImages.find(p => p.id === 'ai-avatar');

  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = "auto";
      const scrollHeight = textareaRef.current.scrollHeight;
      const maxHeight = 200; // max height 
      textareaRef.current.style.height = `${Math.min(scrollHeight, maxHeight)}px`;
    }
  }, [input]);

  const handleSend = () => {
    if (input.trim() === "") return;

    const userMessage: Message = {
      id: Date.now().toString(),
      sender: "user",
      content: input,
      avatar: (
        <Avatar className="h-8 w-8">
          {userAvatar && <AvatarImage src={userAvatar.imageUrl} alt="User" data-ai-hint={userAvatar.imageHint} />}
          <AvatarFallback><User className="h-4 w-4" /></AvatarFallback>
        </Avatar>
      ),
    };

    const aiMessage: Message = {
      id: (Date.now() + 1).toString(),
      sender: "ai",
      content: "This is a placeholder response from the AI. The actual response would be generated by the selected model.",
      avatar: (
        <Avatar className="h-8 w-8">
          {aiAvatar && <AvatarImage src={aiAvatar.imageUrl} alt="AI" data-ai-hint={aiAvatar.imageHint} />}
          <AvatarFallback><Bot className="h-4 w-4" /></AvatarFallback>
        </Avatar>
      ),
    };

    setMessages((prev) => [...prev, userMessage, aiMessage]);
    setInput("");
  };

  const handlePromptClick = (prompt: string) => {
    setInput(prompt);
  };
  
  return (
    <div className="flex flex-col flex-1 bg-card overflow-hidden">
      <ScrollArea className="flex-1 p-4">
        <div className="max-w-4xl mx-auto w-full space-y-6">
          {messages.length === 0 ? (
            <InitialPrompts onPromptClick={handlePromptClick} />
          ) : (
            messages.map((msg) => <ChatMessage key={msg.id} message={msg} />)
          )}
        </div>
      </ScrollArea>

      <footer className="p-4 border-t border-border/20">
        <div className="max-w-4xl mx-auto w-full space-y-4">
            <div className="flex gap-2">
                <Button variant="outline" className="bg-background">
                    <Library className="mr-2 h-4 w-4" />
                    Library
                </Button>
                <Button variant="outline" className="bg-background">
                    <Plus className="mr-2 h-4 w-4" />
                    Add Context
                </Button>
                 <Button variant="outline" size="icon" className="bg-background">
                    <LinkIcon className="h-4 w-4" />
                 </Button>
                 <Button variant="outline" size="icon" className="bg-background">
                    <Mic className="h-4 w-4" />
                 </Button>
            </div>
          <div className="relative">
            <Textarea
              ref={textareaRef}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  handleSend();
                }
              }}
              placeholder="Send message"
              className="pr-28 text-base resize-none"
              rows={1}
            />
            <div className="absolute top-1/2 right-2 transform -translate-y-1/2 flex items-center">
              <Button size="lg" onClick={handleSend} disabled={!input.trim()} className="bg-primary text-primary-foreground h-9">
                <Send className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
